### ISSUE TITLE
想借鉴本庫的kua但是发现下面疑惑，望解答，感谢

### ISSUE THREAD

**Issue by Anber55** [LawssssCat/rime-userdata-backup#26]
想借鉴本庫中的2、3個lua，觉得很不错，但本人没有代码基础，发现说有的lua都是联通的，如果只拿走其中的几个lua會导致打不了字，所以请教一下，如何讓单个的lua，例如url这个lua拆出來放到我的方案里，對應的schema、rime.lua、应该怎么设置，感激不尽

**Comment by LawssssCat** [comment]
对照 [librime-lua 脚本开发指南](https://github.com/hchunhui/librime-lua/wiki/Scripting) 一行行搬。
前提要知道 lua 语法和 lua module 加载顺序。

**Comment by Anber55** [comment]
您好，我已经看过了，尝试了很多次，还是失败了，请教了一个大佬，也不会引用，才疏学浅，打扰您了，感谢您之前的回复
